var panelsData = [
    {
        "Cabinet ID": "GBMS 00900102",        "Rm_Name": "AS CR90",        "Rm_Code": "1T2 139",
        "Interface Type": "UPS, WLS",
        "LL": "-",        "HL": "UPS, WLS",
        "AI": 0,        "DI": 1,        "DO": 0,        "HL__1": "?",
        "AI_M": 0,        "DI_M": 1,        "DO_M": 0,        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900103",        "Rm_Name": "Sump Pump Room",        "Rm_Code": "1T2 065",
        "Interface Type": "PD",
        "LL": "SWSP-1-05, SWSU-1-09, SWSU-1-10",        "HL": "LCP(D)-1005 PM",
        "AI": 0,        "DI": 14,        "DO": 2,        "HL__1": "?",
        "AI_M": 0,        "DI_M": 2,        "DO_M": 1,        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900104",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 083",
        "Interface Type": "LTG",
        "LL": "EXL_S16A_P4_18_NDB1_1A&1B, 2A&2B, 3, 4",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 13,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900105",
        "Rm_Name": "AA T1D(PS) Equipment Cleaning Room",
        "Rm_Code": "1T2 002",
        "Interface Type": "PD",
        "LL": "LCP(D)-1013 Incomer, WWSP-1-07, WWSU-1-13&14",
        "HL": "LCP(D)-1013 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900106",
        "Rm_Name": "AHU Room",
        "Rm_Code": "1T2 133",
        "Interface Type": "PD",
        "LL": "LCP(D)-1012 Incomer, SWSP-1-06, SWSU-1-11&23, RWSP-1-03, RWSU-1-05&6",
        "HL": "LCP(D)-1012 PM",
        "AI": 0,
        "DI": 27,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900107",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 272",
        "Interface Type": "EXL",
        "LL": "EXL_S16A_N8_23_NDB1_1A&1B, 2A&2B, 5, 6",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 13,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900108",
        "Rm_Name": "AHU Room",
        "Rm_Code": "1T2 226",
        "Interface Type": "PD",
        "LL": "LCP(D)-1002 Incomer, LCP(D)-1014 Incomer, SWSP-1-02, SWSU-1-03&4, RWSP-1-02, RWSU-1-03&4",
        "HL": "LCP(D)-1002, 1014 PM",
        "AI": 0,
        "DI": 31,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900109",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "1T2 203",
        "Interface Type": "LVSB",
        "LL": "LVSB-S16a CBS13A306 Incoming, LVSB-S16a Battery charger, LVSB-S16a CBS16A301-5 Outgoing,\nLVSB-S16a ACBS13A201 Incoming, LVSB-S16a CBS16A201-10 Outgoing, LVSB-S16a CBS13B105 Incoming, LVSB-S16a CBS16A101-5 Outgoing",
        "HL": "LVSB-S16a PM",
        "AI": 0,
        "DI": 111,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 8,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900110",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "1T2 203",
        "Interface Type": "LVSB, LTG",
        "LL": "External Lighting, LVSB-S16b CBS14A306 Incoming, LVSB-S16b Battery charger, LVSB-S16b CBS16B301-4 Outgoing, LVSB-S16b ACBS14A201 Incoming, LVSB-S16b CBS16B201-10 Outgoing, LVSB-S16c CBS13A401 Incoming, LVSB-S16c Battery charger, LVSB-S16c CBS16C401-4 Outgoing",
        "HL": "LVSB-S16b&c PM",
        "AI": 0,
        "DI": 109,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 8,
        "DO_M": 1,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900111",
        "Rm_Name": "CBS Room",
        "Rm_Code": "1T2 224",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900112",
        "Rm_Name": "Sump Pump Room",
        "Rm_Code": "1T2 211",
        "Interface Type": "PD",
        "LL": "LCP(D)-1012 Incomer, WWSP-1-06, WWSU-1-11&12",
        "HL": "LCP(D)-1012 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910102",
        "Rm_Name": "Traction Power Room",
        "Rm_Code": "1P 001",
        "Interface Type": "LTG",
        "LL": "EXL_S3_L4_6_NDB1_Z1, Z2 & Z3, EXL_B4_E1_C8",
        "HL": "-",
        "AI": 0,
        "DI": 9,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910103",
        "Rm_Name": "Storage Room",
        "Rm_Code": "1P 006",
        "Interface Type": "LTG",
        "LL": "EXL_C55, 56, 55A & EXL_C1A",
        "HL": "-",
        "AI": 0,
        "DI": 35,
        "DO": 20,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 2,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910104",
        "Rm_Name": "Sump Pump And Tank Room",
        "Rm_Code": "1T2 553",
        "Interface Type": "PD",
        "LL": "LCP(D)-1004 Incomer, SWSP-1-04, SWSU-1-07&8",
        "HL": "LCP(D)-1004 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910105",
        "Rm_Name": "Lobby",
        "Rm_Code": "1T2 502",
        "Interface Type": "PD, LTG",
        "LL": "SU-SP-L1-03, SU-SP-L1-05&6, EXL_S3_M_11_NDB1_C1-C6, SP-SP-L1-01, SU-SU-L1-01&2, SP-SP-L1-02, SU-SU-L1-03&04",
        "HL": "",
        "AI": 0,
        "DI": 8,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0102",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 414",
        "Interface Type": "PD, LTG",
        "LL": "LCP(D)-1007 Incomer, RWSP-1-01, RWSU-1-01&02, EXL_S7A_K4_18_NDB1_1-4AB, 5ABC, 6AB",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 42,
        "DO": 28,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 4,
        "DO_M": 3,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0103",
        "Rm_Name": "TVS & MCC Room",
        "Rm_Code": "1T2 400",
        "Interface Type": "LVSB",
        "LL": "LVSB-S17a CBS7A302 Incoming, LVSB-S17a Battery Charger, LVSB-S17a CBS17A301-4 Outgoing, LVSB-S18a CBS8A302 Incoming, LVSB-S18a Battery Charger, LVSB-S18a CBS18A301-4 Outgoing",
        "HL": "LV SB S17a, S18a PM",
        "AI": 0,
        "DI": 33,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0104",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 315",
        "Interface Type": "LTG",
        "LL": "TBC",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 1,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095A0102",
        "Rm_Name": "AS CC95A",
        "Rm_Code": "1T2 159",
        "Interface Type": "UPS, WLS, PD",
        "LL": "LCP(D)-1003 Incomer, SWSP-1-03, SWSU-1-05&06",
        "HL": "UPS, WLDS, LCP(D)-1003 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095A0103",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 154",
        "Interface Type": "LTG",
        "LL": "EXL_S14B_P8_11_NDB1_1AB,",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095A0104",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 143",
        "Interface Type": "LTG, EV",
        "LL": "EXL_S14B_P8_15_NDB1_1, 2, 2AB, 3AB",
        "HL": "BHS-EV",
        "AI": 0,
        "DI": 13,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095A0105",
        "Rm_Name": "BHS Maintenance Store",
        "Rm_Code": "1T2 100",
        "Interface Type": "PD",
        "LL": "LCP(D)-1001 Incomer, SWSP-1-01, SWSU-1-01&02",
        "HL": "LCP(D)-1001 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095B0102",
        "Rm_Name": "AS CC95B",
        "Rm_Code": "1T2 069",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095B0103",
        "Rm_Name": "Sump Pump Room",
        "Rm_Code": "1T2 087",
        "Interface Type": "PD",
        "LL": "LCP(D)-1008 Incomer, WWSP-1-02, WWSU-1-03&04",
        "HL": "LCP(D)-1008 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095B0104",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 046",
        "Interface Type": "PD, LTG?",
        "LL": "LCP(D)-1009 Incomer, WWSP-1-03, WWSU-1-05&06",
        "HL": "LCP(D)-1009 PM, MCCB PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096A0102",
        "Rm_Name": "AS CC96A",
        "Rm_Code": "1T2 106",
        "Interface Type": "UPS, WLDS, PD",
        "LL": "LCP(D)-1011 Incomer, WWSP-1-05, WWSU-1-09&10",
        "HL": "UPS, WLDS, LCP(D)-1005 PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096A0103",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 109",
        "Interface Type": "PD, LTG",
        "LL": "LCP(D)-1010 Incomer, WWSP-1-04, WWSU-1-07&08, EXL_S14B_T4_12_NDB1_1AB & 2",
        "HL": "LCP(D)-1010 PM, MCCB PM",
        "AI": 0,
        "DI": 22,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096B0102",
        "Rm_Name": "AS CC96B",
        "Rm_Code": "1T2 120",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096B0103",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 124",
        "Interface Type": "LTG",
        "LL": "EXL_S14B_T4_18_NDB1_1AB",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210102",
        "Rm_Name": "Electrical Room (1-E8)",
        "Rm_Code": "1T2 414",
        "Interface Type": "LTG",
        "LL": "ELP_T1SP_1_18_K4_ELPDB102_C15-21, ELP_T1SP_1_18_K4_ELPDB111_C22-30",
        "HL": "-",
        "AI": 0,
        "DI": 33,
        "DO": 32,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 3,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210103",
        "Rm_Name": "T1 Skypier BHS Tunnel",
        "Rm_Code": "BHS",
        "Interface Type": "LTG",
        "LL": "ELP_P2_1_F_7_EDB4_C1-7, ELP_P2_1_F_7_EDB5_C8-14",
        "HL": "-",
        "AI": 0,
        "DI": 29,
        "DO": 28,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 3,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220102",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1T2 046",
        "Interface Type": "LTG",
        "LL": "ELP_T1SP_1_16_L4_ELPDB112_C1-3, 5, 6",
        "HL": "-",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220103",
        "Rm_Name": "APM Depot Electrical Room",
        "Rm_Code": "APM",
        "Interface Type": "LTG",
        "LL": "ELP_DEP7_1_7_F_EDB2_C9-12",
        "HL": "-",
        "AI": 0,
        "DI": 9,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910202",
        "Rm_Name": "CR91",
        "Rm_Code": "2P 004",
        "Interface Type": "UPS",
        "LL": "UPS-CR91-1&2",
        "HL": "UPS-202a, UPS-202b",
        "AI": 0,
        "DI": 9,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910203",
        "Rm_Name": "Lift Machine Room",
        "Rm_Code": "G 1054",
        "Interface Type": "LIFT",
        "LL": "Existing Lift",
        "HL": "-",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00910205",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "2T2 512",
        "Interface Type": "LVSB",
        "LL": "LVSB-S1d ACBS1B302 Incoming, Battery charger,Outgoing (CBS1D101-5 , APM 6/01, APM 3/02, COMM 10/01, EM 19/01, MSS 15/01); LVSB-S1e ACBS1B402 Incomer, Battery charger, Outgoing (ACBS43, LVSB-S1e S43 ATS, CBS1E101 , EM 16/01,  MS 16/01, MS 10/01, MS 11/01, EM 15/01); LVSB-S1f ACBS2B401 Incomer, Battery charger,  Outgoing (ACBS43, S43 ATS, CBS1F101-103, FS 14/01, FS 15/01&02, LFT 10/01, MS 10/03, MS 14/01); LVSB-S1g ACBS2B301 Incomer, Battery charger,  Outgoing (CBS1G101-104, COMM 10/01, EM 15/02, TBE 15/02, HS 15/01, APM 3/01, L&P 15/01)",
        "HL": "LVSB-S1d, e, f, g PM",
        "AI": 0,
        "DI": 189,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 15,
        "DO_M": 0,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0202",
        "Rm_Name": "AS CR92N",
        "Rm_Code": "2T2 003",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0203",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2T2 044",
        "Interface Type": "LTG",
        "LL": "EXL_S15B_M4_18_NDB1_C1, 2AB, 3AB, 4AB, 5, 6",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 17,
        "DO": 16,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0204",
        "Rm_Name": "LVSwitch Room",
        "Rm_Code": "2T2 315",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S15B_N_23_NDB1_1AB, 2, 2AB, 3AB, EXL_S15B_N_23_NDB4_1AB, 2AB; LVSB-S15a ACB307 Incomer, Battery charger, Outgoing (CB302-308), ACB209 Incoming, Outgoing (CB201-210)",
        "HL": "LVSB-S15a PM",
        "AI": 0,
        "DI": 113,
        "DO": 22,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 2,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 092N0205",
        "Rm_Name": "LVSwitch Room",
        "Rm_Code": "2T2 315",
        "Interface Type": "LVSB",
        "LL": "LVSB-S15b ACB307 Incoming, ACB301 Outgoing, Battery charger, CB302-306 Outgoing, ACB209 Incoming, CB201-210 Outgoing, ACB109 Incoming, CB101-107 Outgoing",
        "HL": "LVSB-S15b PM",
        "AI": 0,
        "DI": 122,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 4,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 00900202",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2T2 005",
        "Interface Type": "LTG, UPS",
        "LL": "EXL_S15B_Q_18_NDB1_1, 2AB",
        "HL": "MCCB PM, UPS",
        "AI": 0,
        "DI": 7,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0302",
        "Rm_Name": "CC95X",
        "Rm_Code": "0SA 056",
        "Interface Type": "LTG, UPS",
        "LL": "EXL_OSA_E4_12_NDB1_15L2, BL2&3, 2L3, 3L2, 3L3, 4L1, 4L2, 12L1, 16L3, 13L1, 13L3, 6L1, 6L2, 4L3, 15L1, 2L2",
        "HL": "MCCB PM, UPS",
        "AI": 0,
        "DI": 37,
        "DO": 34,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 3,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0303",
        "Rm_Name": "Genset Room",
        "Rm_Code": "0SA 001",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-S0002&3 Incomer, Fuel Pump , Daily Fuel Tank, CAT.2 Storage Fuel Tank; GEN-S0001 to 3; GEN SB-S28 Battery Charger, ACB100 Incoming, ACB103&4 Outgoing; GEN SB-S29 Battery Charger, ACB100 Incoming, ACB101 Outgoing; GEN SB-S30 Battery Charger, ACB100 Incoming, ACB101 Outgoing",
        "HL": "MCCB PM, UPS",
        "AI": 4,
        "DI": 113,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0304",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 038",
        "Interface Type": "LVSB",
        "LL": "LVSB-S1, S1b",
        "HL": "LVSB-S1, S1b PM",
        "AI": 0,
        "DI": 142,
        "DO": 9,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0305",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 038",
        "Interface Type": "LVSB",
        "LL": "LVSB-S1a",
        "HL": "LVSB-S1a PM",
        "AI": 0,
        "DI": 151,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0306",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 044",
        "Interface Type": "LVSB",
        "LL": "LVSB-S2, S2b",
        "HL": "LVSB-S2, S2b PM",
        "AI": 0,
        "DI": 135,
        "DO": 9,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0307",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 044",
        "Interface Type": "LVSB",
        "LL": "LVSB-S2a, S2a1, S2a2",
        "HL": "LVSB-S2a PM",
        "AI": 0,
        "DI": 173,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 13,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0308",
        "Rm_Name": "APM Genset Room",
        "Rm_Code": "0SA 005",
        "Interface Type": "LVSB",
        "LL": "600V SB ACB Incoming, Battery Charger",
        "HL": "600V SB PM",
        "AI": 0,
        "DI": 6,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0309",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "0SA 054",
        "Interface Type": "LTG",
        "LL": "EXL_S1A_E4_12_NDB1_6-10",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0310",
        "Rm_Name": "APM LV Switch Room",
        "Rm_Code": "0SA 007",
        "Interface Type": "LVSB",
        "LL": "600V LV-SB-ACB1&ACB2 Incoming, Battery Charger, ACB1&2 Outgoing, ATS, Section",
        "HL": "600V LV-SB PM",
        "AI": 0,
        "DI": 24,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0311",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 013",
        "Interface Type": "LVSB",
        "LL": "LVSB-S3 ACBS3AS, 4AS, 5AS Incoming, ACB101-104, 201 Outgoing, Battery Charger, Section Switch x4; LVSB-S3a ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S28103, ATS S3101; LVSB-S3b ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S29101, ATS S3D101; LVSB-S3c ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S30101, ATS S3103; LVSB-S3d ACB201 Incoming, ACB101&102 Outgoing, Battery Charger",
        "HL": "LVSB S3, S3a, S3b, S3c, S3d PM",
        "AI": 0,
        "DI": 161,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 15,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0312",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0SA 018",
        "Interface Type": "LVSB",
        "LL": "LVSB-S4 ACBS3AS, 4AS, 5AS Incoming, ACB101-104, 201 Outgoing, Battery Charger, Section Switch x4; LVSB-S4a ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S28103, ATS S3101; LVSB-S4b ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S29101, ATS S3D101; LVSB-S4c ACB201 Incomer, Battery Charger, CB101&102 Outgoing, Section Switch x1, ATS S30101, ATS S3103; LVSB-S4d ACB201 Incoming, ACB101&102 Outgoing, Battery Charger",
        "HL": "LVSB S4, S4a, S4b, S4c, S4d PM",
        "AI": 0,
        "DI": 161,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 15,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0314",
        "Rm_Name": "Water Pump Room",
        "Rm_Code": "0SA 076",
        "Interface Type": "PD",
        "LL": "LCP(P)-S3002 Incomer, FLBP-3-S01 & 02; LCP(P)-S3003 Incomer, CLBP-3-S01 & 02; LCP(P)-3-S01 Incomer, PWBP-3-S01 & 02",
        "HL": "-",
        "AI": 0,
        "DI": 70,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 6,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0315",
        "Rm_Name": "F&B Storage",
        "Rm_Code": "0SA 078",
        "Interface Type": "CBS, UPS, LTG",
        "LL": "EXL_OSA_E4_19_NDB1,",
        "HL": "CBS, UPS",
        "AI": 0,
        "DI": 41,
        "DO": 40,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 3,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0316",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "0SA 026",
        "Interface Type": "LTG",
        "LL": "EXL_S1A_E4_19_NDB1",
        "HL": "??",
        "AI": 0,
        "DI": 15,
        "DO": 14,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0317",
        "Rm_Name": "F.S. Generator Room",
        "Rm_Code": "0SA 035",
        "Interface Type": "GENSET",
        "LL": "GEN-S0009, Daily Fuel Tank, GEN SB-S25",
        "HL": "GEN SB-S25 PM",
        "AI": 1,
        "DI": 30,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 3,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0319",
        "Rm_Name": "Generator Room",
        "Rm_Code": "0SA 092",
        "Interface Type": "GENSET",
        "LL": "GEN-S0006 & 12, GEN SB-S27, 31",
        "HL": "GEN SB-S27, S31 PM",
        "AI": 0,
        "DI": 58,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 5,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095X0320",
        "Rm_Name": "Generator Room",
        "Rm_Code": "0SA 032",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-S0001 Incomer, Fuel Pump , Daily Fuel Tank, CAT.2 Storage Fuel Tank; GEN-S0005, 7, 8, 10; GEN SB-S32 to 34 Battery Charger, ACB100 Incoming, ACB101 Outgoing; GEN SB-S26 Battery Charger, ACB100 Incoming, ACB101&102 Outgoing",
        "HL": "no PM",
        "AI": 2,
        "DI": 126,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 10,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0302",
        "Rm_Name": "AS CR93N",
        "Rm_Code": "3T2 178",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0303",
        "Rm_Name": "LM",
        "Rm_Code": "3P 164",
        "Interface Type": "LIFT",
        "LL": "Existing Lift",
        "HL": "-",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0304",
        "Rm_Name": "",
        "Rm_Code": "",
        "Interface Type": "LIFT, LTG",
        "LL": "Existing Lift C10, PE-09 to 11; EXL_P377_NDB1, EXL_G3_L_D_NDB1 to 4",
        "HL": "-",
        "AI": 0,
        "DI": 75,
        "DO": 30,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 6,
        "DO_M": 3,
        "HL_M": 0,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0305",
        "Rm_Name": "North E",
        "Rm_Code": "-",
        "Interface Type": "LIFT",
        "LL": "Existing Lift",
        "HL": "-",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0306",
        "Rm_Name": "Lift Mac",
        "Rm_Code": "-",
        "Interface Type": "LIFT",
        "LL": "Existing Lift",
        "HL": "-",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0307",
        "Rm_Name": "AHU Room",
        "Rm_Code": "3T2 125",
        "Interface Type": "PD",
        "LL": "LCP(D)-3431 Incomer, SWSP-3-04, SWSU-3-07&8",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0308",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 117",
        "Interface Type": "LTG",
        "LL": "EXL_S23A_K4_2_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 17,
        "DO": 16,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 093N0309",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 056",
        "Interface Type": "LTG",
        "LL": "EXL_S23A_H8_4_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 7,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 094N0302",
        "Rm_Name": "AS CR94N",
        "Rm_Code": "3T2 874",
        "Interface Type": "UPS, WLS, LTG",
        "LL": "-",
        "HL": "UPS, WLS, MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0302",
        "Rm_Name": "AS CR95N",
        "Rm_Code": "3T2 808",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0303",
        "Rm_Name": "UPS Room",
        "Rm_Code": "3T2 885",
        "Interface Type": "UPS, CBS",
        "LL": "-",
        "HL": "UPS, CBS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0304",
        "Rm_Name": "Clean Agent Gas Room",
        "Rm_Code": "3T2 667",
        "Interface Type": "PD",
        "LL": "LCP(D)-3001, 11, 13, SWSP-3-01, SWSU-3-01&2, WWSP-3-03, WWSU-3-05&6, RWSP-3-01, RWSU-3-01&2",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 46,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 4,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0305",
        "Rm_Name": "Genset Room",
        "Rm_Code": "3T2 890",
        "Interface Type": "GENSET",
        "LL": "LCP(FP)-M0001, GEN-M0001&2, GEN SB-S39 & 40",
        "HL": "GEN SB PM",
        "AI": 2,
        "DI": 75,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 7,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0306",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 891",
        "Interface Type": "LVSB",
        "LL": "LVSB-S7, 7a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 133,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0307",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 891",
        "Interface Type": "LVSB",
        "LL": "LVSB-S7b, 7c, 7d",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 151,
        "DO": 15,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0308",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 821",
        "Interface Type": "LVSB",
        "LL": "LVSB-S8, 8a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 121,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0309",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 821",
        "Interface Type": "LVSB",
        "LL": "LVSB-S8b, 8c&d",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 165,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 12,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0310",
        "Rm_Name": "Genset Room",
        "Rm_Code": "3T2 330",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-M0001, GEN-M0003 to 6, GEN SB-S47 to 50",
        "HL": "GEN SB PM",
        "AI": 2,
        "DI": 147,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 12,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0311",
        "Rm_Name": "AHU Room",
        "Rm_Code": "3T2 722",
        "Interface Type": "PD",
        "LL": "LCP(D)-3005, 7, 15, SWSP-3-05, SWSU-3-09&10, SWSP-3-07, SWSU-3-13&14, RWSP-3-03, RWSU-3-05&6",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 46,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 4,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0312",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 521",
        "Interface Type": "LVSB",
        "LL": "LVSB-S9, 9a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 152,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0313",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 521",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S9A_K_25_NDB1; LVSB-S9b, 9c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 153,
        "DO": 30,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 12,
        "DO_M": 2,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0314",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 532",
        "Interface Type": "LVSB",
        "LL": "LVSB-S10, 10a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 152,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 12,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 095N0315",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 532",
        "Interface Type": "LVSB",
        "LL": "LVSB-S10b, 10c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 147,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096N0302",
        "Rm_Name": "AS CR96N",
        "Rm_Code": "3T2 355",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096N0303",
        "Rm_Name": "Genset Room",
        "Rm_Code": "3T2 340",
        "Interface Type": "GENSET",
        "LL": "GEN SB-S41, S42, S43; LCP(FP)-M0002, GEN-M0010, 11, 12",
        "HL": "GEN SB PM",
        "AI": 0,
        "DI": 105,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096N0304",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 369",
        "Interface Type": "LTG",
        "LL": "EXL_S10A_Q_23_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 15,
        "DO": 14,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096N0305",
        "Rm_Name": "UPS Room",
        "Rm_Code": "3T2 346",
        "Interface Type": "UPS, CBS",
        "LL": "-",
        "HL": "UPS, CBS",
        "AI": "",
        "DI": "",
        "DO": "",
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 097N0302",
        "Rm_Name": "AS CR97N",
        "Rm_Code": "3T2 422",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 097N0303",
        "Rm_Name": "Sump Pump Room",
        "Rm_Code": "3T2 638",
        "Interface Type": "PD",
        "LL": "LCP(D)-3002, SWSP-3-02, SWSU-3-03&04",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 16,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 097N0304",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 611",
        "Interface Type": "PD, LTG",
        "LL": "LCP(D)-3012, 3014, RWSP-3-02, RWSU-3-03&04, WWSP-3-04, WWSU-3-07&08; EXL_S14B_N4_18_NDB1",
        "HL": "LCP(D) & MCCB PM",
        "AI": 0,
        "DI": 39,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 097N0305",
        "Rm_Name": "Sump Pump Room",
        "Rm_Code": "3T2 613",
        "Interface Type": "PD",
        "LL": "LCP(D)-3006, SWSP-3-06, SWSU-3-11&12",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 098N0302",
        "Rm_Name": "AS CR98N",
        "Rm_Code": "3T2 173",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 098N0303",
        "Rm_Name": "North E",
        "Rm_Code": "-",
        "Interface Type": "LIFT",
        "LL": "Existing Lift",
        "HL": "-",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 098N0304",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 156",
        "Interface Type": "PD, LTG, LIFT",
        "LL": "LCP(D)-3002, SWSP-3-03, SWSU-3-05&06; EXL_S24A_M8_2_NDB1; Lift VLP-02",
        "HL": "LCP(D) & MCCB PM",
        "AI": 0,
        "DI": 35,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 098N0305",
        "Rm_Name": "AHU Room",
        "Rm_Code": "3T2 180",
        "Interface Type": "PD",
        "LL": "LCP(D)-3010, WWSP-3-02, WWSU-3-03&04",
        "HL": "LCP(D) & MCCB PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 098N0306",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 039",
        "Interface Type": "LTG",
        "LL": "EXL_S24A_P4_4_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210302",
        "Rm_Name": "Water Tank and Pump Room",
        "Rm_Code": "3T2 210",
        "Interface Type": "PD, WLS",
        "LL": "LCP(P)-3001 to 4, PWBP-3-01&02, CLBP-3-01&02, IRBP-3-01&02, FLBP-3-01&02,",
        "HL": "LCP(D) PM, WLS",
        "AI": 0,
        "DI": 91,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 7,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210303",
        "Rm_Name": "Lift Machine Room",
        "Rm_Code": "3T2 202",
        "Interface Type": "LIFT, WLS",
        "LL": "Exiting Lift VLP-03",
        "HL": "WLS",
        "AI": 0,
        "DI": 12,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210304",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3T2 243",
        "Interface Type": "LTG, WLS",
        "LL": "EXL_S5A_K4_10_NDB1 & 4",
        "HL": "MCCB PM, WLS",
        "AI": 0,
        "DI": 27,
        "DO": 26,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210305",
        "Rm_Name": "Store Room",
        "Rm_Code": "3T2 865",
        "Interface Type": "PD",
        "LL": "LCP(D)-3008, WWSP-3-08, WWSU-3-15&16",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210306",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 856",
        "Interface Type": "LVSB",
        "LL": "LVSB-S5, 5a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 142,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210307",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 856",
        "Interface Type": "LVSB, LTG",
        "LL": "LVSB-S5b; EXL_S5A_G_12_NDB1 & 4",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 131,
        "DO": 27,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 2,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210308",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 869",
        "Interface Type": "LVSB",
        "LL": "LVSB-S6, 6a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 151,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 13,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210309",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 869",
        "Interface Type": "LVSB",
        "LL": "LVSB-S6b, 6c, 5c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 191,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 13,
        "DO_M": 1,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210310",
        "Rm_Name": "Cable Duct Room & LV Switch Room",
        "Rm_Code": "3T2 872",
        "Interface Type": "LVSB",
        "LL": "LVSB-S3e, f, g; LVSB-S4e, f, g",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 139,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220302",
        "Rm_Name": "AA Office",
        "Rm_Code": "3T2 270",
        "Interface Type": "LTG",
        "LL": "EXL_S11A_M8_10_NDB1, 4",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 29,
        "DO": 28,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 2,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220303",
        "Rm_Name": "Sprinkler Pump & Tank Room",
        "Rm_Code": "3T2 280",
        "Interface Type": "PD",
        "LL": "LCP(D)-3009, WWSP-3-01, WWSU-3-01&2",
        "HL": "LCP(D) PM",
        "AI": 0,
        "DI": 16,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220304",
        "Rm_Name": "Genset Room",
        "Rm_Code": "3T2 294",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-M0002, GEN-M0007 to 9, GEN SB-S44 to 46",
        "HL": "GEN SB S44, 45, 46 PM",
        "AI": 2,
        "DI": 111,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220305",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 308",
        "Interface Type": "LVSB",
        "LL": "LVSB S11, 11a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 148,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220306",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 308",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S11A_Q8_12_NDB1; LVSB S11b",
        "HL": "LVSB & MCCB PM",
        "AI": 0,
        "DI": 123,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220307",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 316",
        "Interface Type": "LVSB",
        "LL": "LVSB S12, 12a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 154,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220308",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 316",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S12A_Q8_14_NDB1; LVSB S12b",
        "HL": "LVSB & MCCB PM",
        "AI": 0,
        "DI": 126,
        "DO": 37,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 3,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220309",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 320",
        "Interface Type": "LVSB",
        "LL": "LVSB S13, 13a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 138,
        "DO": 7,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220310",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 320",
        "Interface Type": "LVSB",
        "LL": "LVSB S13b, 11c, 12c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 169,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 12,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220311",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 325",
        "Interface Type": "LVSB",
        "LL": "LVSB S14, 14b",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 124,
        "DO": 9,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220312",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "3T2 325",
        "Interface Type": "LVSB",
        "LL": "LVSB S14a",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 117,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0302",
        "Rm_Name": "AS CC96X",
        "Rm_Code": "0NA 071",
        "Interface Type": "UPS, WLDS",
        "LL": "-",
        "HL": "UPS, WLDS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0304",
        "Rm_Name": "Genset Room",
        "Rm_Code": "0NA 011",
        "Interface Type": "GENSET, LTG",
        "LL": "LCP(FP)-N0001, GEN-N0008, GEN SB-S68, EXL_S54C_S8_20_NDB1",
        "HL": "GEN SB S68v PM",
        "AI": 0,
        "DI": 50,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 4,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0305",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 016",
        "Interface Type": "LVSB",
        "LL": "LVSB S51, 51a, LVSB S51b, 51c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 184,
        "DO": 11,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 14,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0306",
        "Rm_Name": "Generator Room",
        "Rm_Code": "0NA 099",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-N0001, GEN-N0001 to 3, GEN SB-S61 to 63",
        "HL": "GEN SB PM",
        "AI": 2,
        "DI": 108,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0307",
        "Rm_Name": "UPS",
        "Rm_Code": "0NA 027",
        "Interface Type": "UPS, CBS",
        "LL": "-",
        "HL": "UPS, CBS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0308",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 018",
        "Interface Type": "LVSB",
        "LL": "LVSB S52, 52a, 52b, 52c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 187,
        "DO": 11,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 14,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0309",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 030",
        "Interface Type": "LVSB",
        "LL": "LVSB S53, 53a, 53b, 53c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 133,
        "DO": 12,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0310",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 030",
        "Interface Type": "LVSB",
        "LL": "LVSB S53c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 107,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0311",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 036",
        "Interface Type": "LVSB",
        "LL": "LVSB S55, 55a, 55b, 55c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 193,
        "DO": 11,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 15,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0312",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "0NA 054",
        "Interface Type": "LTG",
        "LL": "MCCB",
        "HL": "-",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0313",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 042",
        "Interface Type": "LVSB",
        "LL": "LVSB S56, 56a, 56b, 56c",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 186,
        "DO": 11,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 14,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0314",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 055",
        "Interface Type": "LVSB",
        "LL": "LVSB S54, 54a, 54b",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 142,
        "DO": 13,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0315",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "0NA 051",
        "Interface Type": "LVSB",
        "LL": "LVSB S54c, 54d",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 151,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0316",
        "Rm_Name": "Water Pump & Tank Room",
        "Rm_Code": "0NA 059",
        "Interface Type": "PD",
        "LL": "LCP(P)-N3001 to 3,  PWBP-3-N01&2, CLBP-3-N01&2, FLBP-3-N01&2",
        "HL": "LCP(P) PM",
        "AI": 0,
        "DI": 69,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 6,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 096X0317",
        "Rm_Name": "Generator Room",
        "Rm_Code": "0NA 095",
        "Interface Type": "GENSET",
        "LL": "LCP(G)-N0002, GEN-N0004 to 7, GEN SB-S64 to 67",
        "HL": "LCP, SB PM",
        "AI": 2,
        "DI": 138,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 1,
        "DI_M": 11,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 96X0302HV",
        "Rm_Name": "AA High Voltage Switch Room",
        "Rm_Code": "0NA 034",
        "Interface Type": "HV",
        "LL": "Battery Charger BC-03",
        "HL": "-",
        "AI": 0,
        "DI": 2,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 96X0303HV",
        "Rm_Name": "AA High Voltage Switch Room",
        "Rm_Code": "0NA 051",
        "Interface Type": "HV",
        "LL": "Battery Charger BC-02",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 2,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 96X0304HV",
        "Rm_Name": "High Voltage Generator Room",
        "Rm_Code": "0NA 075",
        "Interface Type": "HV GENSET",
        "LL": "LCP(G)-N0003,",
        "HL": "",
        "AI": 0,
        "DI": 15,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 0,
        "HL_M": 0,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 96X0305HV",
        "Rm_Name": "High Voltage Switch Room",
        "Rm_Code": "0NA 079",
        "Interface Type": "HV",
        "LL": "Battery Charger BC-01",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 2,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210402",
        "Rm_Name": "CR121",
        "Rm_Code": "4T2 021",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01210403",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "4T2 021",
        "Interface Type": "LTG, CBS",
        "LL": "EXL_S6A_K4_10_NDB1",
        "HL": "MCCB PM, CBS",
        "AI": 0,
        "DI": 9,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220402",
        "Rm_Name": "AS CR122",
        "Rm_Code": "4T2 046",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220403",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "4T2 021",
        "Interface Type": "LTG, CBS",
        "LL": "EXL_S12A_M_10_NDB1",
        "HL": "MCCB PM, CBS",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0502",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1SA 001",
        "Interface Type": "LTG, WLS",
        "LL": "EXL_S1A_D8_10_NDB1, EXL_S1A_F_10_CDB1",
        "HL": "WLS, MCCB PM",
        "AI": 0,
        "DI": 7,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0503",
        "Rm_Name": "AHU Room",
        "Rm_Code": "1SA 024",
        "Interface Type": "LTG, WLS",
        "LL": "EXL_S1A_D8_21_NDB1, EXL_S1A_E8_20_CDB1",
        "HL": "WLS, MCCB PM",
        "AI": 0,
        "DI": 17,
        "DO": 16,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 2,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123A0502",
        "Rm_Name": "AS CC123A",
        "Rm_Code": "5T2 388",
        "Interface Type": "UPS, WLS, LTG",
        "LL": "-",
        "HL": "UPS, WLS, MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123A0503",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "5T2 389",
        "Interface Type": "LVSB",
        "LL": "LVSB S21a, c, d",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 135,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123A0504",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "5T2 389",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S21B_J4_14_NDB1, LVSB S21b",
        "HL": "LVSB, MCCB PM",
        "AI": 0,
        "DI": 119,
        "DO": 35,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 10,
        "DO_M": 3,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123B0502",
        "Rm_Name": "AS CC123B",
        "Rm_Code": "5T2 830",
        "Interface Type": "UPS, WLS, LTG",
        "LL": "EXL_S8A_H_24_NDB1",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124A0502",
        "Rm_Name": "AS CC124A",
        "Rm_Code": "5T2 528",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124A0503",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "5T2 529",
        "Interface Type": "LVSB",
        "LL": "LVSB S22a, c, d",
        "HL": "LVSB PM",
        "AI": 0,
        "DI": 141,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124A0504",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "5T2 529",
        "Interface Type": "LVSB, LTG",
        "LL": "EXL_S22B_N4_14_NDB1, LVSB S22b",
        "HL": "LVSB, MCCB PM",
        "AI": 0,
        "DI": 114,
        "DO": 26,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 9,
        "DO_M": 2,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124B0502",
        "Rm_Name": "AS CC124B",
        "Rm_Code": "5T2 858",
        "Interface Type": "UPS, WLS, LTG",
        "LL": "EXL_S9A_M8_25_NDB1",
        "HL": "UPS, WLS, MCCB PM",
        "AI": 0,
        "DI": 12,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220502",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "5T2 262",
        "Interface Type": "LTG",
        "LL": "EXL_S24A_P4_6_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 11,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01220503",
        "Rm_Name": "AHU Room",
        "Rm_Code": "5T2 273",
        "Interface Type": "WLS",
        "LL": "-",
        "HL": "WLS-503",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": "combine to 01220502"
    },
    {
        "Cabinet ID": "GBMS 01210502",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "5T2 212",
        "Interface Type": "LTG",
        "LL": "EXL_S23A_H8_6_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 9,
        "DO": 8,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0502",
        "Rm_Name": "AS CC124X",
        "Rm_Code": "1NA 072",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0503",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1NA 024",
        "Interface Type": "LVSB EV",
        "LL": "LVSB-EV-01",
        "HL": "PM",
        "AI": 0,
        "DI": 24,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0504",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "1NA 055",
        "Interface Type": "WLS, LTG",
        "LL": "-",
        "HL": "WLS, MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0602",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2SA 002",
        "Interface Type": "LTG",
        "LL": "EXL_S1A_F_10_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 7,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0603",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2SA 015",
        "Interface Type": "LTG",
        "LL": "EXL_S1A_E8_20_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01230602",
        "Rm_Name": "AS CR123",
        "Rm_Code": "6T2 013",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01230603",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6T2 028",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 4,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01000602",
        "Rm_Name": "AS CR100",
        "Rm_Code": "6T2 261",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01000603",
        "Rm_Name": "UPS Room",
        "Rm_Code": "6T2 256",
        "Interface Type": "LVSB, LTG",
        "LL": "LVSB-S19, S20",
        "HL": "LVSB, MCCB Powermeter",
        "AI": 0,
        "DI": 35,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 3,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01000604",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6T2 269",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01240602",
        "Rm_Name": "AS CR124",
        "Rm_Code": "6T2 084",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 01240603",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6T2 051",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124C0602",
        "Rm_Name": "AS CC124C",
        "Rm_Code": "6T2 211",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124C0603",
        "Rm_Name": "CBS Room",
        "Rm_Code": "6T2 205",
        "Interface Type": "CBS",
        "LL": "-",
        "HL": "CBS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": "Combine to 124C0603"
    },
    {
        "Cabinet ID": "GBMS 124C0604",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6T2 204",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 3,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123D0602",
        "Rm_Name": "AS CC123D",
        "Rm_Code": "6T2 305",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123D0603",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "6T2 321",
        "Interface Type": "CBS, PV, LVSB, LTG",
        "LL": "LVSB-S23a, b, c; PV",
        "HL": "CBS, PV, LVSB, MCCB PM",
        "AI": 0,
        "DI": 147,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 11,
        "DO_M": 0,
        "HL_M": 5,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124D0602",
        "Rm_Name": "AS CC124D",
        "Rm_Code": "6T2 193",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124D0603",
        "Rm_Name": "LV Switch Room",
        "Rm_Code": "6T2 421",
        "Interface Type": "CBS, PV, LVSB, LTG",
        "LL": "LVSB-S24a, b, c;",
        "HL": "CBS, PV, LVSB, MCCB PM",
        "AI": 0,
        "DI": 151,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 12,
        "DO_M": 0,
        "HL_M": 5,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0602",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2NA 002",
        "Interface Type": "LTG",
        "LL": "EXL_S54C_S_19_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0603",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "2NA 010",
        "Interface Type": "LTG",
        "LL": "EXL_S53C_S_13_NDB1_7",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123E0702",
        "Rm_Name": "AS CC123E",
        "Rm_Code": "7T2 079",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123E0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 058",
        "Interface Type": "LTG",
        "LL": "EXL_S21B_K4_15_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123F0702",
        "Rm_Name": "AS CC123F",
        "Rm_Code": "7T2 049",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123F0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 027",
        "Interface Type": "LTG",
        "LL": "EXL_S21B_J4_15_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123G0702",
        "Rm_Name": "AS CC123G",
        "Rm_Code": "7T2 019",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123G0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 013",
        "Interface Type": "LTG",
        "LL": "EXL_S21B_H4_15_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123I0702",
        "Rm_Name": "AS CC123I",
        "Rm_Code": "7T2 409",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123I0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 417",
        "Interface Type": "LTG",
        "LL": "EXL_S8A_K4_23_NDB1_1AB, 2A, 3, 4",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123I0704",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 431",
        "Interface Type": "LTG",
        "LL": "EXL_S8A_J8_23_NDB1_1AB, 2-4",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 11,
        "DO": 10,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123I0705",
        "Rm_Name": "AHU Room",
        "Rm_Code": "7T2 433",
        "Interface Type": "CBS, WLS",
        "LL": "-",
        "HL": "CBS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124E0702",
        "Rm_Name": "AS CC124E",
        "Rm_Code": "7T2 119",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124E0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 113",
        "Interface Type": "LTG",
        "LL": "EXL_S22B_M8_15_NDB1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124F0702",
        "Rm_Name": "AS CC124F",
        "Rm_Code": "7T2 149",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124F0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 153",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124G0702",
        "Rm_Name": "AS CC124G",
        "Rm_Code": "7T2 176",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124G0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 062",
        "Interface Type": "LTG",
        "LL": "EXL_S22B_P8_15_NDB1_1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124I0702",
        "Rm_Name": "AS CC124I",
        "Rm_Code": "7T2 259",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124I0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 278",
        "Interface Type": "LTG",
        "LL": "EXL_S9A_M4_23_NDB1_1AB",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124I0704",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 208",
        "Interface Type": "LTG",
        "LL": "EXL_S9A_P8_24_NDB1_1",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 2,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0702",
        "Rm_Name": "AS CC123X",
        "Rm_Code": "3SA 026",
        "Interface Type": "UPS, WLS",
        "LL": "-",
        "HL": "UPS, WLS",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "R",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 123X0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "7T2 278",
        "Interface Type": "LTG",
        "LL": "EXL_S1A_F_10_NDB1_1AB, 2",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 7,
        "DO": 6,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0702",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3NA 001",
        "Interface Type": "EV, LTG",
        "LL": "LVSB-EV-02, EXL_S54C3_S_19_NDB1_6, 7",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 25,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 2,
        "DO_M": 1,
        "HL_M": 1,
        "Cabinet_Size": "B",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0703",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "3NA 015",
        "Interface Type": "LTG",
        "LL": "EXL_S53C3_S_13_NDB1_9",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0802",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "4NA 001",
        "Interface Type": "LTG",
        "LL": "EXL_S54C4_S_19_NDB1_7",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 2,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0803",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "4NA 015",
        "Interface Type": "LTG",
        "LL": "EXL_S53C4_S_13_NDB1_9",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0902",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "5NA 001",
        "Interface Type": "LTG",
        "LL": "EXL_S54C5_S_19_NDB1_7",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X0903",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "5NA 015",
        "Interface Type": "LTG",
        "LL": "EXL_S53C5_S_13_NDB1_9",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 3,
        "DO": 2,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X1002",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6NA 001",
        "Interface Type": "LTG",
        "LL": "EXL_S54C6_S_19_NDB1_3, 4",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 5,
        "DO": 4,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    },
    {
        "Cabinet ID": "GBMS 124X1003",
        "Rm_Name": "Electrical Room",
        "Rm_Code": "6NA 015",
        "Interface Type": "LTG",
        "LL": "-",
        "HL": "MCCB PM",
        "AI": 0,
        "DI": 1,
        "DO": 0,
        "HL__1": "?",
        "AI_M": 0,
        "DI_M": 1,
        "DO_M": 0,
        "HL_M": 1,
        "Cabinet_Size": "S",
        "Remark": ""
    }
]

// Tabel Configuration
$.extend($.fn.dataTable.defaults, {
    searching: true,
    ordering: false,
    paging: false,
    info: true,
    dom: 'Bfrtip',
});

// Submission dataTable
$('#panelTable').dataTable({
    "data": panelsData,
    "columns": [
        { "data": "Cabinet ID" },
        { "data": "Rm_Name" },
        { "data": "Rm_Code" },
        { "data": "Interface Type" },
        { "data": "LL" },
        { "data": "HL" },
        { "data": "AI" },
        { "data": "DI" },
        { "data": "DO" },
        { "data": "HL__1" },
        { "data": "AI_M" },
        { "data": "DI_M" },
        { "data": "DO_M" },
        { "data": "HL_M" },
        { "data": "Cabinet_Size" },
        { "data": "Remark" },
    ]
});

$(document).ready(function() {
    $('#panelTable').DataTable();
//    $('#commsTable').DataTable();
});

var tableName = "panelTable"
// Auto update table width
// refresh the table
var tableWidth = 0; var tableWidthCalc;

function calculateTableWidth(tableName) {
    var table = document.getElementById(tableName);
    tableWidthCalc = innerWidth - table.getBoundingClientRect().left - table.getBoundingClientRect().width;
}

// resize table if needed
function resizeTable(tableName) {
    var table = document.getElementById(tableName);
    if (tableWidthCalc < innerWidth) {
        table.style.width = "100%";
    } else if (tableWidthCalc > innerWidth) {
        table.style.width = (tableWidthCalc - innerWidth) + "px";
    }
}
// calculate table width on initial load
calculateTableWidth(tableName);

// trigger resize event on page load
resizeTable(tableName);

// calculate table width on window resize event
addEventListener("resize", function (event) {
     console.log("Window resized");
     calculateTableWidth();}, false);
